name: Database script - Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: lynxnetworkbrasil/liquibase/.github/workflow/database-pull-request.yml@main
