name: Database script - Production

on:
  push:
    branches:
      - main
      - develop
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: lynxnetworkbrasil/liquibase/.github/workflows/database-production/action.yml@main
