name: Database script - Production

on:
  push:
    branches:
      - main
      - develop
      - stage
  workflow_dispatch:

jobs:
  build:
    uses: lynxnetworkbrasil/liquibase/.github/workflows/database-production.yml@main
